{% set name = "h5io_browser" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/h5io_browser-{{ version }}.tar.gz
  sha256: 9110d61ac58b8b9c07cb472794977b36f7f10eb29fbb20565697b056f2a52497

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - h5io
    - h5py
    - numpy
    - pandas
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >=3.8
    - h5io ==0.2.2
    - h5py >=3.6.0,<=3.10.0
    - numpy >=1.23.5,<=1.26.4
    - pandas >=1.5.3,<=2.2.1

test:
  imports:
    - h5io_browser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h5io/h5io_browser
  summary: Easy navigation and data storage for HDF5
  description: |
    The h5io_browser package extends the h5io interface by 
    providing a pointer h5io_browser.Pointer to a specific 
    path inside the hierarchical structure of the HDF5 file. 
    With this pointer, data can be read, stored, copied and 
    deleted from the HDF5 file, while at the same time simplifying 
    the navigation inside the hierarchy of the file.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/h5io/h5io_browser
  dev_url: https://github.com/h5io/h5io_browser

extra:
  recipe-maintainers:
    - jan-janssen
