{% set name = "h5io_browser" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32851a4c4c1582b03f1454f35a9a4c48ed90d5cd5828d653ad966a1c81e1d315

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - h5io
    - hdf5
    - numpy
    - pandas
    - versioneer
    - toml
  run:
    - python >=3.8
    - h5io =0.2.0
    - h5py >=3.6.0,<=3.10.0
    - numpy >=1.23.5,<=1.26.3
    - pandas >=1.5.3,<=2.1.4

test:
  imports:
    - h5io_browser
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/h5io/h5io_browser
  summary: 'Easy navigation and data storage for HDF5'
  description: |
    The h5io_browser package extends the h5io interface by 
    providing a pointer h5io_browser.Pointer to a specific 
    path inside the hierarchical structure of the HDF5 file. 
    With this pointer, data can be read, stored, copied and 
    deleted from the HDF5 file, while at the same time simplifying 
    the navigation inside the hierarchy of the file.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/h5io/h5io_browser
  dev_url: https://github.com/h5io/h5io_browser

extra:
  recipe-maintainers:
    - jan-janssen
