{% set name = "h5io_browser" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/h5io_browser-{{ version }}.tar.gz
  sha256: 3941a322fbb63020ec2c07b59566365b1cde290bfc185b7e5b1d095e58712302

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - h5io
    - h5py
    - numpy
    - pandas
    - setuptools
    - versioneer ==0.29
    - pip
  run:
    - python >={{ python_min }}
    - h5io >=0.2.2,<=0.2.5
    - h5py >=3.6.0,<=3.13.0
    - numpy >=1.23.5,<=2.2.4
    - pandas >=1.5.3,<=2.3.0

test:
  imports:
    - h5io_browser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/h5io/h5io_browser
  summary: Easy navigation and data storage for HDF5
  description: |
    The h5io_browser package extends the h5io interface by 
    providing a pointer h5io_browser.Pointer to a specific 
    path inside the hierarchical structure of the HDF5 file. 
    With this pointer, data can be read, stored, copied and 
    deleted from the HDF5 file, while at the same time simplifying 
    the navigation inside the hierarchy of the file.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://github.com/h5io/h5io_browser
  dev_url: https://github.com/h5io/h5io_browser

extra:
  recipe-maintainers:
    - jan-janssen
